name: "Run CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-checks:
    uses: ./.github/workflows/checks.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
